import { library, config } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import '@fortawesome/fontawesome-svg-core/styles.css';
import {
    faArrowRightFromBracket,
    faArrowRotateRight,
    faArrowUpRightFromSquare,
    faBars,
    faBell,
    faBuildingColumns,
    faCalendarDays,
    faChartColumn,
    faCheck,
    faChevronDown,
    faChevronLeft,
    faChevronRight,
    faCircleCheck,
    faClipboardCheck,
    faClock,
    faDatabase,
    faDownload,
    faEllipsis,
    faEnvelope,
    faEye,
    faFileArrowUp,
    faFileCircleCheck,
    faFileLines,
    faGauge,
    faGear,
    faGlobe,
    faHouse,
    faLocationDot,
    faLock,
    faMagnifyingGlass,
    faMoon,
    faPen,
    faPhone,
    faPlus,
    faReceipt,
    faRightToBracket,
    faScrewdriverWrench,
    faSun,
    faUser,
    faUserPlus,
    faUserTie,
    faUsers,
    faXmark,
    faCircleInfo,
    faFlask,
    faFloppyDisk,
    faLayerGroup,
    faTrashCan,
    faUserCheck,
    faUserPen,
    faChevronUp,
    faCircleExclamation,
    faFilePdf,
    faFileWord,
    faPaperPlane,
    faTriangleExclamation,
    faArrowRight,
    faClockRotateLeft,
    faComment,
    faPenToSquare,
    faUserXmark,
    faGavel,
    faBook,
    faFileExcel,
    faNewspaper,
    faPersonChalkboard,
} from '@fortawesome/free-solid-svg-icons';
import { faFileLines as farFileLines, faUser as farUser } from '@fortawesome/free-regular-svg-icons';

// CSS is imported above, so don't let the library inject it again
config.autoAddCss = false;

library.add(
    faArrowRightFromBracket, faArrowRotateRight, faArrowUpRightFromSquare, faBars, faBell,
    faBuildingColumns, faCalendarDays, faChartColumn, faCheck, faChevronDown, faChevronLeft,
    faChevronRight, faCircleCheck, faClipboardCheck, faClock, faDatabase, faDownload, faEllipsis, faEnvelope, faEye,
    faFileArrowUp, faFileCircleCheck, faFileLines, faGauge, faGear, faGlobe, faHouse,
    faLocationDot, faLock, faMagnifyingGlass, faMoon, faPen, faPhone, faPlus, faReceipt, faRightToBracket,
    faScrewdriverWrench, faSun, faUser, faUserPlus, faUserTie, faUsers, faXmark,
    faCircleInfo, faFlask, faFloppyDisk, faLayerGroup, faTrashCan, faUserCheck, faUserPen,
    faChevronUp, faCircleExclamation, faFilePdf, faFileWord, faPaperPlane, faTriangleExclamation,
    faArrowRight, faClockRotateLeft,
    faComment, faPenToSquare, faUserXmark,
    faGavel,
    faBook, faFileExcel, faNewspaper, faPersonChalkboard,
    farFileLines, farUser,
);

export { FontAwesomeIcon };
